blank_issues_enabled: false
contact_links: []
issue_templates:
  - name: ğŸ› Bug report
    description: Report found application bug
    title: "[BUG] "
    labels: [bug]
    assignees: []
    template: bug_report.md

  - name: âœ¨ New feature
    description: Suggest new feature or improvements
    title: "[FEATURE] "
    labels: [enhancement]
    assignees: []
    template: feature_request.md

  - name: ğŸ”¨ Refactoring
    description: Report refactoring needs
    title: "[REFACTOR] "
    labels: [refactor]
    assignees: []
    template: refactor_task.md

  - name: ğŸ—ï¸ Technical debt
    description: Technical problems to fix later
    title: "[TECH DEBT] "
    labels: [tech-debt]
    assignees: []
    template: tech_debt.md

  - name: âœ… Test task
    description: Adding tests request or tests fixing
    title: "[TEST] "
    labels: [tests]
    assignees: []
    template: test_task.md
